Asset-Management.Web/Controllers/ReturnAssetController.cs
using Asset_Management.Repository;
using Asset_Management.Service;
using Asset_Management.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Asset_Management.Web.Controllers
{
    [AllowAnonymous]
    public class ReturnAssetController : Controller
    {
        private readonly AssetService _assetService;
        private readonly ReturnAssetService _returnAssetService;

        public ReturnAssetController(ApplicationDbContext context)
        {
            _assetService = new AssetService(context);
            _returnAssetService = new ReturnAssetService(context);
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            ViewBag.Asset = new SelectList(_assetService.GetUsedAsset(), "Id", "AssetNameWithSnSpec");
            return View();
        }
        /*
                [HttpPost]
                public IActionResult Update([Bind("Id, AssetId, Location, PicId, SendDate, ReturnDate")] AssetHistoryReq req)
                {
                    if (ModelState.IsValid)
                    {
                        var returnAsset = _returnAssetService.ReadAssetHistory(req);
                        var entity = new AssetHistoryEntity();
                        _returnAssetService.UpdateAssetHistory(req);
                        return Redirect("Index");
                    }
                    return View("Edit", req);
                }*/

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Update(AssetHistoryReq req)
        {

            var entity = _returnAssetService.ReadAssetHistory(req);
            _returnAssetService.UpdateAssetHistory(req, entity);
            return Redirect("/Asset/Index");

        }

    }
}

Asset-Management.Web/Views/ReturnAsset/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Asset_Management.ViewModel.AssetHistoryReq

@{
    ViewBag.Title = "Asset History - Create New Data";
    Layout = "_Layout";
}

<h2>Return Asset History</h2>

<form asp-controller="ReturnAsset" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <div class="form-group">
        <label asp-for="AssetId">Asset Id</label>
        <select type="text" asp-for="AssetId" class="form-control" asp-items="@ViewBag.Asset">
            <option selected>Select Asset</option>
        </select>
        <span asp-validation-for="AssetId" class="text-danger"></span>
    </div>
    <input type="hidden" asp-for="Location" />
    <input type="hidden" asp-for="PicId" />
    <input type="hidden" asp-for="SendDate" />
    <div class="form-group">
        <label asp-for="ReturnDate">Return Date</label>
        <input asp-for="ReturnDate" class="form-control" ></input>
        <span asp-validation-for="ReturnDate" class="text-danger"></span>
    </div>
    <div class="pt-2 pb-2">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}