Asset-Management.Web/Controllers/AssetHistoryController.cs
using Asset_Management.Repository;
using Asset_Management.Service;
using Asset_Management.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Asset_Management.Web.Controllers
{
    public class AssetHistoryController : Controller
    {
        private readonly AssetHistoryService _assetHistoryService;
        private readonly AssetService _assetService;
        private readonly PicService _picService;

        public AssetHistoryController(ApplicationDbContext context)
        {
            _assetHistoryService = new AssetHistoryService(context);
            _assetService = new AssetService(context);
            _picService = new PicService(context);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            var data = _assetHistoryService.GetAssetHistory();
            return View(data);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Add()
        {
            ViewBag.Asset = new SelectList(_assetService.GetAssets(), "Id", "AssetNameWithSnSpec ");
            ViewBag.Pic = new SelectList(_picService.GetPics(), "Id", "FullName");
            return View();
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult AddModal()
        {
            ViewBag.Asset = new SelectList(_assetService.GetAssets(), "Id", "AssetNameWithSnSpec");
            ViewBag.Pic = new SelectList(_picService.GetPics(), "Id", "FullName");
            return PartialView("_Add");
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save([Bind("AssetId, RequestId, Location, PicId, SendDate")] AssetHistoryReq req)
        {
            if (ModelState.IsValid)
            {
                _assetHistoryService.CreateAssetHistory(req);
                return Redirect("Index");
            }
            return View("Add", req);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Edit(long? id)
        {
            var assetHistory = _assetHistoryService.ReadAssetHistory(id);
            return View(assetHistory);
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult Update([Bind("Id, AssetId, Location, PicId, SendDate, ReturnDate")] AssetHistoryReq req)
        {
            if (ModelState.IsValid)
            {
                _assetHistoryService.UpdateAssetHistory(req);
                return Redirect("Index");
            }
            return View("Edit", req);
        }


    }
}

Asset-Management.Web/Views/AssetHistory/Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Asset_Management.ViewModel.AssetHistoryReq

@{
    ViewBag.Title = "Asset History - Create New Data";
    Layout = "_Layout";
}

<h2>Create New Asset History</h2>

<form asp-controller="AssetHistory" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="AssetId">Asset Id</label>
        <select type="text" asp-for="AssetId" class="form-control" asp-items="@ViewBag.Asset">
            <option selected>Select Asset</option>
        </select>
        <span asp-validation-for="AssetId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Location">Location</label>
        <input asp-for="Location" class="form-control"></input>
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PicId">PIC Name</label>
        <select type="text" asp-for="PicId" class="form-control" asp-items="@ViewBag.Pic">
            <option selected>Select Asset</option>
        </select>
        <span asp-validation-for="PicId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SendDate">Send Date</label>
        <input asp-for="SendDate" class="form-control">< /input>
        <span asp-validation-for="SendDate" class="text-danger"></span>
    </div>
    <div class="pt-2 pb-2">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Asset-Management.Web/Views/AssetHistory/Edit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Asset_Management.ViewModel.AssetHistoryReq

@{
    ViewBag.Title = "Asset History";
    // Admin History
    ViewBag.namePage = "Create Return Date";
    ViewBag.Level1 = "Asset";
    ViewBag.Level2 = "AssetHistory";

    // Admin chose asset
    Layout = "adminLayout";
}

<!-- Main content -->
<section class="content">
    <div class="row">
        <div class="col-md-5">
            <!-- general form elements disabled -->
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title">Form Edit Asset</h3>
                </div>
                <!-- /.card-header -->
                <div class="card-body">
                    <form asp-controller="AssetHistory" asp-action="Update" method="post">
                        <input type="hidden" asp-for="Id" />
                        <input type="hidden" asp-for="AssetId" />
                        <input type="hidden" asp-for="Location" />
                        <input type="hidden" asp-for="PicId" />
                        <input type="hidden" asp-for="SendDate" />
                        <div class="row">
                            <div class="col-sm-12">
                                <!-- text input -->
                                <div class="form-group">
                                    <label asp-for="ReturnDate">Return Date</label>
                                    <input asp-for="ReturnDate" type="date" class="form-control" placeholder="Return Date Asset">
                                    <span asp-validation-for="ReturnDate" class="text-danger"></span>
                                </div>
                            </div>
                        </div>
                        
                        <div class="row">
                            <div class="col-12">
                                <a asp-action="Index" class="btn btn-secondary">Back</a>
                                <input type="submit" value="Create" class="btn btn-success float-right">
                            </div>
                        </div>

                    </form>
                </div>
                <!-- /.card-body -->
            </div>
            <!-- /.card -->
        </div>
    </div>
</section>
<!-- /.content -->

@*

<h2>Create New Asset History</h2>

<form asp-controller="AssetHistory" asp-action="Update" method="post">
    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="AssetId" />
    <input type="hidden" asp-for="Location" />
    <input type="hidden" asp-for="PicId" />
    <input type="hidden" asp-for="SendDate" />
    <div class="form-group">
        <label asp-for="ReturnDate">Return Date</label>
        <input asp-for="ReturnDate" class="form-control"></input>
        <span asp-validation-for="ReturnDate" class="text-danger"></span>
    </div>
    <div class="pt-2 pb-2">
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>*@

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Asset-Management.Web/Views/AssetHistory/Index.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model IEnumerable<Asset_Management.ViewModel.AssetHistoryResponse>
@{
    ViewBag.Title = "Asset History";
    // Admin History
    ViewBag.namePage = "Daftar Asset History";
    ViewBag.Level1 = "Asset";
    ViewBag.Level2 = "AssetHistory";

    // Admin chose asset
    Layout = "adminLayout";
}

<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">

                <div class="card">
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">

                            <thead>
                                <tr>
                                    <th>Id</th>
                                    <th>Asset Name</th>
                                    <th>specification</th>
                                    <th>Serial Number</th>
                                    <th>PurchaseYear</th>
                                    <th>Location</th>
                                    <th>Pic Name</th>
                                    <th>Send Date</th>
                                    <th>Return Date</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>@item.Id</td>
                                        <td>@item.AssetName</td>
                                        <td>@item.Specification</td>
                                        <td>@item.SerialNumber</td>
                                        <td>@item.PurchaseYear</td>
                                        <td>@item.Location</td>
                                        <td>@item.PicName</td>
                                        <td>@item.SendDate</td>
                                        <td>@item.ReturnDate</td>
                                        <td>
                                            <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-sm btn-warning">Return Asset</a>
                                        </td>
                                    </tr>
                                }
                            </tbody>

                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>

<div id="add-modal" class="modal" tabindex="-1">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title">Add New Asset</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
                <p>Modal body text goes here.</p>
            </div>

        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $("#btn-add").on("click", function (e) {
            e.preventDefault();
            $.ajax({
                url: "/AssetHistory/AddModal",
                type: "GET",
                dataType: "html",
                success: function (data) {
                    $("#add-modal").find(".modal-body").html(data);
                    $("#add-modal").modal("show");
                }
            });

        });
    </script>
}

Asset-Management.Web/Views/AssetHistory/_Add.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@model Asset_Management.ViewModel.AssetHistoryReq
@{
    ViewBag.Title = "Asset History - Create New Data";
}

<form asp-controller="AssetHistory" asp-action="Save" method="post">
    <div class="form-group">
        <label asp-for="AssetId">Asset Id</label>
        <select type="text" asp-for="AssetId" class="form-control" asp-items="@ViewBag.Asset">
            <option selected>Select Asset</option>
        </select>
        <span asp-validation-for="AssetId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="Location">Location</label>
        <input asp-for="Location" class="form-control"></input>
        <span asp-validation-for="Location" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="PicId">PIC Name</label>
        <select type="text" asp-for="PicId" class="form-control" asp-items="@ViewBag.Pic">
            <option selected>Select Asset</option>
        </select>
        <span asp-validation-for="PicId" class="text-danger"></span>
    </div>

    <div class="form-group">
        <label asp-for="SendDate">Send Date</label>
        <input asp-for="SendDate" class="form-control" />
        <span asp-validation-for="SendDate" class="text-danger"></span>
    </div>

    <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
    </div>
</form>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}