Asset-Management.Web/Controllers/AssetController.cs
using Asset_Management.Repository;
using Asset_Management.Service;
using Asset_Management.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Asset_Management.Web.Controllers
{
    public class AssetController : Controller
    {
        private readonly AssetService _service;

        public AssetController(ApplicationDbContext context)
        {
            _service = new AssetService(context);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            var assets = _service.GetAssets();
            return View(assets);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult AddModal()
        {
            return PartialView("_Add");
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save([Bind("AssetName, Specification, SerialNumber, PurchaseYear, Used")] AssetModel req)
        {
            if (ModelState.IsValid)
            {
                _service.CreateAsset(new AssetEntity(req));
                return Redirect("Index");
            }
            return View("Add", req);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult History(long? id)
        {
            var asset = _service.ReadHistoryAssetById(id);
            return View(asset);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Edit(long? id)
        {
            var asset = _service.ReadAsset(id);
            return View(asset);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Update([Bind("Id, AssetName, Specification, SerialNumber, PurchaseYear, Used")] AssetModel req)
        {
            if (ModelState.IsValid)
            {
                _service.UpdateAsset(req);
                return Redirect("Index");
            }
            return View("Edit", req);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            _service.DeleteAsset(id);
            return Redirect("/Asset");
        }

    }
}

Asset-Management.Web/Controllers/AuditController.cs
using Asset_Management.Repository;
using Asset_Management.Service;
using Asset_Management.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Asset_Management.Web.Controllers
{
    public class AuditController : Controller
    {
        private readonly AuditService _service;

        public AuditController(ApplicationDbContext context)
        {
            _service = new AuditService(context);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            var audit = _service.GetUnvalidatedAudits();
            return View(audit);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Detail(long? id)
        {
            var audit = _service.ReadAudit(id);
            return View(audit);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Validated()
        {
            var audit = _service.GetValidatedAudits();
            return View(audit);
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Validate(long? id)
        {
            var audit = _service.ReadAuditReq(id);
            return View(audit);
        }
        [AllowAnonymous]
        [HttpPost]
        public IActionResult UpdateAudit(
            [Bind("Id, AssetHistoryId, Condition, TypeWindows, WindowsLicenseUrl, TypeOffice, OfficeLicenseUrl, Antivirus, AssetPhotoUrl, Result")] AuditValidationReq req)
        {
            if (ModelState.IsValid)
            {
                _service.UpdateAudit(req);
                return Redirect("Index");
            }
            return View("Validate", req);
        }
    }
}

Asset-Management.Web/Controllers/FormAuditController.cs
using Asset_Management.Repository;
using Asset_Management.Service;
using Asset_Management.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace Asset_Management.Web.Controllers
{
    public class FormAuditController : Controller
    {
        private readonly AuditService _auditService;
        private readonly AssetHistoryService _assetHistoryService;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public FormAuditController(ApplicationDbContext context, IWebHostEnvironment webHostEnvironment)
        {
            _auditService = new AuditService(context);
            _assetHistoryService = new AssetHistoryService(context);
            _webHostEnvironment = webHostEnvironment;
        }
        [AllowAnonymous]
        public string UploadedFile(IFormFile file)
        {
            string uniqueFileName = null;
            if (file != null)
            {
                string uploadsFolder = Path.Combine(_webHostEnvironment.WebRootPath, "upload_audit");
                string fileType = file.FileName.Split('.').Last();
                uniqueFileName = Guid.NewGuid().ToString() + "." + fileType; ;
                string filePath = Path.Combine(uploadsFolder, uniqueFileName);
                using (var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    file.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
        [AllowAnonymous]
        [HttpGet]
        public IActionResult Index()
        {
            ViewBag.AssetHistory = new SelectList(_assetHistoryService.GetPicFromAssetHistory(), "Id", "PicName");
            return View();
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save(
            [Bind("AssetHistoryId, Condition, TypeWindows, WindowsLicense, TypeOffice, OfficeLicense, Antivirus, AssetPhoto")] AuditReq req)
        {
            if (ModelState.IsValid)
            {
                req.WindowsLicenseUrl = UploadedFile(req.WindowsLicense);
                req.OfficeLicenseUrl = UploadedFile(req.OfficeLicense);
                req.AssetPhotoUrl = UploadedFile(req.AssetPhoto);
                _auditService.CreateAudit(req);

                return Redirect("/FormAudit/Success");
            }
            return View("Index", req);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Success()
        {
            return View();
        }

    }
}

Asset-Management.Web/Controllers/RequestController.cs
using Asset_Management.Repository;
using Asset_Management.Service;
using Asset_Management.ViewModel;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Asset_Management.Web.Controllers
{
    public class RequestController : Controller
    {
        private readonly RequestAssetService _service;

        public RequestController(ApplicationDbContext context)
        {
            _service = new RequestAssetService(context);
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Add()
        {
            return View();
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult AddModal()
        {
            return PartialView("_Add");
        }

        [AllowAnonymous]
        [HttpGet]
        public IActionResult Detail(long? id)
        {
            var requestAsset = _service.ReadRequestAsset(id);
            return View(requestAsset);
        }

        [AllowAnonymous]
        [HttpPost]
        public IActionResult Save([Bind("PicName, PicAddress, Specification, RequestDate")] RequestAssetModel req)
        {
            if (ModelState.IsValid)
            {
                _service.CreateRequestAsset(req);
                return Redirect("Index");
            }
            return View("Add", req);
        }

        [AllowAnonymous]
        public IActionResult Index()
        {
            var request = _service.GetRequests();
            return View(request);
        }
    }
}

Asset-Management.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asset_Management.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asset_Management.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asset_Management.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="IndexLog">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Asset" asp-action="Index">Asset</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="Index">Request Asset</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RequestAsset" asp-action="Index">Approval</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="RequestList" asp-action="Index">Request Asset List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="AssetHistory" asp-action="Index">History</a>
                        </li>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="FormAudit" asp-action="Index">Form Audit</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Index">Audit List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Audit" asp-action="Validated">Validated Audit</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Asset_Management.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Asset-Management.Web/Views/Shared/_LayoutNoLog.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asset_Management.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asset_Management.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Asset_Management.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Asset_Management.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Asset-Management.Web/Views/Shared/adminLayout.cshtml
@*admin*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>@ViewData["Title"] - Asset Management RAPID</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asset_Management.Web.styles.css" asp-append-version="true" />

    @*tambahan*@
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/assets/plugins/fontawesome-free/css/all.min.css">
    <!-- DataTables -->
    <link rel="stylesheet" href="~/assets/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
    <link rel="stylesheet" href="~/assets/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
    <link rel="stylesheet" href="~/assets/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/assets/dist/css/adminlte.min.css">

    @*tambahan 2*@
    <!-- Toastr -->
    <link rel="stylesheet" href="~/asset/plugins/toastr/toastr.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/asset/dist/css/adminlte.min.css">



</head>
<body class="hold-transition sidebar-mini">
    @functions {
        public string drop(string a, string b)
        {
            if (a == b)
            {
                return "menu-open";
            }
            return "";
        }

        public string act(string a, string b)
        {
            if (a == b)
            {
                return "active";
            }
            return "";
        }
    }
    @{
        var inp = ViewData["Level1"].ToString();
        var inp2 = ViewData["Level2"].ToString();
    }
    <div class="wrapper">
        <!-- Navbar -->
        <nav class="main-header navbar navbar-expand navbar-white navbar-light">
            <!-- Left navbar links -->
            <ul class="navbar-nav">
                <li class="nav-item">
                    <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
                </li>
                <!-- <li class="nav-item d-none d-sm-inline-block">
                  <a href="../../index3.html" class="nav-link">Home</a>
                </li>
                <li class="nav-item d-none d-sm-inline-block">
                  <a href="#" class="nav-link">Contact</a>
                </li> -->
            </ul>
            <!-- Right navbar links -->
        </nav>
        <!-- /.navbar -->
        <aside class="main-sidebar sidebar-dark-primary elevation-4">
            <!-- Brand Logo -->
            <a href="" class="brand-link">
                <img src="~/assets/dist/img/AdminLTELogo.png" alt="AdminLTE Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
                <span class="brand-text font-weight-light">ASSET-MANAGEMENT</span>
            </a>

            <!-- Sidebar -->
            <div class="sidebar">
                <!-- Sidebar user (optional) -->
                <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                    <div class="image">
                        <img src="~/assets/dist/img/user2-160x160.jpg" class="img-circle elevation-2" alt="User Image">
                    </div>
                    <div class="info">
                        <a href="#" class="d-block">Admin</a>
                    </div>
                </div>

                <!-- Sidebar Menu -->
                <nav class="mt-2">
                    <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                        <li class="nav-item @drop(inp, "Request")">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-edit"></i>
                                <p>
                                    Request
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="RequestList" asp-action="Index" class="nav-link @act(inp2, "RequestAsset")">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Daftar Request</p>
                                    </a>
                                </li>

                            </ul>
                        </li>
                            
                        
                        <li class="nav-item @drop(inp,"Asset")">
                            <a href="#" class="nav-link ">
                                <i class="nav-icon fas fa-book"></i>
                                <p>
                                    Aset
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Asset" asp-action="Index" class="nav-link @act(inp2, "AssetList")">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Daftar Aset</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="AssetHistory" asp-action="Index" class="nav-link @act(inp2, "AssetHistory")">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Aset History</p>
                                    </a>
                                </li>
                            </ul>
                        </li>


                        <li class="nav-item @drop(inp,"Audit")">
                            <a href="#" class="nav-link">
                                <i class="nav-icon fas fa-clipboard-list"></i>
                                <p>
                                    Audit
                                    <i class="fas fa-angle-left right"></i>
                                </p>
                            </a>
                            <ul class="nav nav-treeview">
                                <li class="nav-item">
                                    <a asp-controller="Audit" asp-action="Index" class="nav-link @act(inp2, "UnvalidateAudit")">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Daftar Audit</p>
                                    </a>
                                </li>
                                <li class="nav-item">
                                    <a asp-controller="Audit" asp-action="Validated" class="nav-link @act(inp2, "ValidateAudit")">
                                        <i class="far fa-circle nav-icon"></i>
                                        <p>Validated Audit</p>
                                    </a>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </nav>
                <!-- /.sidebar-menu -->
            </div>
            <!-- /.sidebar -->
        </aside>
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            <!-- Content Header (Page header) -->
            <section class="content-header">
                <div class="container-fluid">
                    <div class="row mb-2">
                        <div class="col-sm-6">
                            <h1>@ViewData["namePage"]</h1>
                        </div>
                        <div class="col-sm-6">
                            <ol class="breadcrumb float-sm-right">
                                <li class="breadcrumb-item"><a href="#">Dashboard</a></li>
                                <li class="breadcrumb-item active"> @ViewData["namePage"]</li>
                            </ol>
                        </div>
                    </div>
                </div><!-- /.container-fluid -->
            </section>
            <!-- /.section -->
            @RenderBody()
        </div>
        @*isi content*@
        <footer class="main-footer">
            <div class="float-right d-none d-sm-block">
                <b>Version</b> 3.2.0
            </div>
            <strong>RAPIDTECH<a href="https://adminlte.io"> TIM 1 Raden Soedirman </a> made with &#128151;</strong>
        </footer>
    </div>
    <!-- ./wrapper -->
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*tambahan*@
    <!-- jQuery -->
    <script src="~/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- DataTables  & Plugins -->
    <script src="~/assets/plugins/datatables/jquery.dataTables.min.js"></script>
    <script src="~/assets/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
    <script src="~/assets/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
    <script src="~/assets/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
    <script src="~/assets/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
    <script src="~/assets/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
    <script src="~/assets/plugins/jszip/jszip.min.js"></script>
    <script src="~/assets/plugins/pdfmake/pdfmake.min.js"></script>
    <script src="~/assets/plugins/pdfmake/vfs_fonts.js"></script>
    <script src="~/assets/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
    <script src="~/assets/plugins/datatables-buttons/js/buttons.print.min.js"></script>
    <script src="~/assets/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/assets/dist/js/adminlte.min.js"></script>
    @*    <!-- AdminLTE for demo purposes -->
    <script src="~/assets/dist/js/demo.js"></script>*@

    @*tambahan 2*@
    <!-- SweetAlert2 -->
    <script src="~/asset/plugins/sweetalert2/sweetalert2.min.js"></script>
    <!-- Toastr -->
    <script src="~/asset/plugins/toastr/toastr.min.js"></script>

    @*buat datatables*@
    <script>
        $(function () {
            $("#example1").DataTable({
                "responsive": true, "lengthChange": false, "autoWidth": false,
                "buttons": ["copy", "excel", "pdf", "print", "colvis"]
            }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
            $('#example2').DataTable({
                "paging": true,
                "lengthChange": true,
                "searching": true,
                "ordering": true,
                "info": false,
                "autoWidth": false,
                "responsive": true,
            });
        });
    </script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Asset-Management.Web/Views/Shared/loginLayout.cshtml
@*login*@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Asset Management RAPID</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Asset_Management.Web.styles.css" asp-append-version="true" />

    @*tambahan*@
    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/assets/plugins/fontawesome-free/css/all.min.css">
    <!-- icheck bootstrap -->
    <link rel="stylesheet" href="~/assets/plugins/icheck-bootstrap/icheck-bootstrap.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/assets/dist/css/adminlte.min.css">
</head>
<body class="hold-transition login-page">


    @*
    <div class="container">
    <main role="main" class="pb-3">*@
    @RenderBody()
    @*        </main>
    </div>

    <footer class="border-top footer text-muted">
    <div class="container">
    &copy; 2023 - Asset_Management.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
    </div>
    </footer>*@
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @*tambahan*@
    <!-- jQuery -->
    <script src="~/assets/plugins/jquery/jquery.min.js"></script>
    <!-- Bootstrap 4 -->
    <script src="~/assets/plugins/bootstrap/js/bootstrap.bundle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="~/assets/dist/js/adminlte.min.js"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>